# Generated by Django 2.2.4 on 2019-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'Store'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
