# Generated by Django 2.2.4 on 2019-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191224_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
